# Generated by Django 3.2.6 on 2021-09-03 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_name', models.CharField(max_length=200)),
                ('Statement', models.CharField(max_length=2000)),
                ('Code', models.CharField(max_length=4000)),
                ('Difficulty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Input', models.CharField(max_length=200)),
                ('Output', models.CharField(max_length=200)),
                ('Tc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.problems')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Verdict', models.CharField(max_length=100)),
                ('Submitted', models.DateTimeField(verbose_name='Time Submitted')),
                ('Sol_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.problems')),
            ],
        ),
    ]
